version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: nooonchill/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    image: nooonchill/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: nooonchill/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/media
    ports:
      - 9000:80